#!/usr/bin/env sh
set -ex

IMG_DEV=cpp_hpc_tutorial:dev-latest
IMG_LAB=cpp_hpc_tutorial:lab-latest
PORT=8888

DOCKER_CMDS="\
  --gpus=all \
  -u $(id -u):$(id -g) \
  -h $(hostname) \
  -v $(pwd):/src \
  -v $(pwd)/conan:/.conan \
  -w /src \
  $IMG_DEV \
"

case $1 in
    build)
	rm -r target/ || true
	mkdir -p target
	hpccm --recipe=ci/recipe_dev.py | docker build -t $IMG_DEV -
	hpccm --recipe=ci/recipe_lab.py > target/Dockerfile
        docker build -t $IMG_LAB -f target/Dockerfile .
	;;
    fmt)
	docker run $DOCKER_CMDS bash -c "set -ex && ./ci/fmt"
	;;
    it)
	docker run -it $DOCKER_CMDS bash
	;;
    serve-dev)
	mkdir -p target/local
	docker run -p ${PORT}:8888 \
 -v "$(pwd)/target/local":"/.local" $DOCKER_CMDS bash -c "jupyter-lab --no-browser --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token="" --notebook-dir=/src/labs"
	;;
    serve)
	rm -r target/ || true
	mkdir -p target
	hpccm --recipe=ci/recipe_lab.py > target/Dockerfile
        docker build -t $IMG_LAB -f target/Dockerfile .
	docker run --gpus=all -p ${PORT}:8888 $IMG_LAB
	;;
    *)
	exit 1
	;;
esac
